/// Emits `taro_tokens.g.dart` from a [TokenSet] (02 §14.1): one immutable
/// class per token group (`TaroColorTokens`, `TaroColorBgTokens`, …) with
/// `const` instances per mode (`light`, `dark`), a `reduced` instance for
/// groups with reduced-motion values, and a static `lerp`.
library;

import 'package:taro_dart_tools/src/tokens/token_set.dart';
import 'package:taro_dart_tools/src/tokens/token_values.dart';

/// Generator settings.
final class EmitOptions {
  /// Creates the settings.
  const EmitOptions({
    this.source = 'docs/design/taro.tokens.json',
    this.fontPackage,
    this.prefix = 'Taro',
  });

  /// Source path named in the file header.
  final String source;

  /// The Flutter package that bundles the font families (`TextStyle.package`),
  /// or null for app-level fonts.
  final String? fontPackage;

  /// Class-name prefix.
  final String prefix;
}

/// The Dart source (not yet `dart format`ted) for [set].
String emitTokensDart(
  TokenSet set, {
  EmitOptions options = const EmitOptions(),
}) {
  final root = _Node('', '', const []);
  for (final token in set.tokens.values) {
    var node = root;
    final segments = token.path;
    for (var i = 0; i < segments.length; i++) {
      final key = segments[i];
      node = node.children.putIfAbsent(
        key,
        () => _Node(
          key,
          _fieldName(key, i == 0 ? '' : segments[i - 1]),
          [...node.fieldPath, _fieldName(key, i == 0 ? '' : segments[i - 1])],
        ),
      );
    }
    node.token = token;
  }
  for (final top in root.children.values) {
    if (top.token != null) {
      throw TokenException('${top.key}: top-level tokens need a group');
    }
  }
  return _Emitter(set, options).emit(root);
}

final class _Node {
  _Node(this.key, this.field, this.fieldPath);

  final String key;
  final String field;
  final List<String> fieldPath;
  final Map<String, _Node> children = {};
  DesignToken? token;

  bool get isGroup => token == null;

  Iterable<DesignToken> get tokens sync* {
    if (token != null) yield token!;
    for (final child in children.values) {
      yield* child.tokens;
    }
  }
}

const Set<String> _reserved = {
  'default',
  'switch',
  'case',
  'class',
  'const',
  'final',
  'new',
  'null',
  'true',
  'false',
  'this',
  'super',
  'is',
  'in',
  'var',
  'void',
  'if',
  'else',
  'for',
  'do',
  'while',
  'return',
};

/// The Dart field for JSON key [key] under [parent]: camelCase, and a
/// numeric key takes the parent's first letter (`space.4` → `s4`,
/// `elevation.0` → `e0`).
String _fieldName(String key, String parent) {
  final parts = key.split(RegExp('[-_ ]+')).where((p) => p.isNotEmpty).toList();
  var name = parts.isEmpty
      ? key
      : parts.first +
            parts
                .skip(1)
                .map((p) => p[0].toUpperCase() + p.substring(1))
                .join();
  if (RegExp(r'^\d').hasMatch(name)) {
    name = '${parent.isEmpty ? 'v' : parent[0].toLowerCase()}$name';
  }
  if (!RegExp(r'^[a-zA-Z_]\w*$').hasMatch(name)) {
    throw TokenException('$key: cannot be a Dart name');
  }
  return _reserved.contains(name) ? '${name}Value' : name;
}

String _pascal(String field) => field[0].toUpperCase() + field.substring(1);

final class _Variant {
  const _Variant(this.mode, {this.reduced = false});

  final String mode;
  final bool reduced;
}

final class _Emitter {
  _Emitter(this.set, this.options);

  final TokenSet set;
  final EmitOptions options;
  final StringBuffer out = StringBuffer();

  String className(_Node node) =>
      '${options.prefix}${node.fieldPath.map(_pascal).join()}Tokens';

  String emit(_Node root) {
    out
      ..writeln(
        '// GENERATED by tools/tokens/generate.dart from ${options.source}.',
      )
      ..writeln('// Do not edit: change the tokens and re-run the generator.')
      ..writeln(
        '// ignore_for_file: public_member_api_docs, lines_longer_than_80_chars',
      )
      ..writeln()
      ..writeln("import 'dart:ui' show lerpDouble;")
      ..writeln()
      ..writeln("import 'package:flutter/animation.dart';")
      ..writeln("import 'package:flutter/foundation.dart';")
      ..writeln("import 'package:flutter/painting.dart';")
      ..writeln()
      ..writeln('/// Every token name in ${options.source}, in file order.')
      ..writeln('const List<String> k${options.prefix}TokenNames = <String>[');
    for (final name in set.tokens.keys) {
      out.writeln("  '$name',");
    }
    out
      ..writeln('];')
      ..writeln()
      ..writeln('/// The modes of ${options.source}.')
      ..writeln('const List<String> k${options.prefix}TokenModes = <String>[');
    for (final mode in set.modes) {
      out.writeln("  '$mode',");
    }
    out.writeln('];');
    for (final top in root.children.values) {
      _emitClass(top, topLevel: true);
    }
    return out.toString();
  }

  void _emitClass(_Node node, {required bool topLevel}) {
    final name = className(node);
    final fields = node.children.values.toList();
    out
      ..writeln()
      ..writeln('/// `${_jsonPath(node)}` tokens.')
      ..writeln('@immutable')
      ..writeln('final class $name {')
      ..writeln('  /// Creates the `${_jsonPath(node)}` tokens.')
      ..writeln('  const $name({');
    for (final f in fields) {
      out.writeln('    required this.${f.field},');
    }
    out.writeln('  });');
    if (topLevel) _emitInstances(node);
    for (final f in fields) {
      out.writeln();
      final doc = f.token?.description ?? '`${_jsonPath(f)}`.';
      out
        ..writeln('  /// ${_docLine(doc)}')
        ..writeln('  final ${_type(f)} ${f.field};');
    }
    out
      ..writeln()
      ..writeln('  /// Interpolates between [a] and [b] (theme animations).')
      ..writeln('  static $name lerp($name a, $name b, double t) => $name(');
    for (final f in fields) {
      out.writeln('    ${f.field}: ${_lerp(f)},');
    }
    out
      ..writeln('  );')
      ..writeln('}');
    for (final f in fields.where((f) => f.isGroup)) {
      _emitClass(f, topLevel: false);
    }
  }

  void _emitInstances(_Node node) {
    final tokens = node.tokens.toList();
    final moded = tokens.any((t) => t.isModed || _aliasIsModed(t));
    final first = set.modes.first;
    for (final mode in set.modes) {
      out
        ..writeln()
        ..writeln('  /// The `$mode` mode.');
      if (!moded && mode != first) {
        out.writeln('  static const ${className(node)} $mode = $first;');
        continue;
      }
      out.writeln(
        '  static const ${className(node)} $mode = '
        '${_instance(node, _Variant(mode))};',
      );
    }
    if (tokens.any((t) => t.reducedMotion != null)) {
      out
        ..writeln()
        ..writeln(
          '  /// Reduced-motion values (`\$extensions["$kReducedMotionExtension"]`).',
        )
        ..writeln(
          '  static const ${className(node)} reduced = '
          '${_instance(node, _Variant(first, reduced: true))};',
        );
    }
  }

  bool _aliasIsModed(DesignToken token) {
    final target = TokenSet.aliasOf(token.value);
    return target != null && (set.tokens[target]?.isModed ?? false);
  }

  String _instance(_Node node, _Variant variant) {
    final args = [
      for (final f in node.children.values)
        '${f.field}: ${_argument(f, variant)}',
    ];
    return '${className(node)}(${args.join(', ')},)';
  }

  String _argument(_Node f, _Variant variant) =>
      f.isGroup ? _instance(f, variant) : _value(f.token!, variant);

  String _type(_Node f) {
    if (f.isGroup) return className(f);
    return switch (f.token!.type) {
      'color' => 'Color',
      'dimension' || 'number' => 'double',
      'duration' => 'Duration',
      'cubicBezier' => 'Cubic',
      'shadow' => 'List<BoxShadow>',
      'typography' => 'TextStyle',
      'fontWeight' => 'FontWeight',
      'fontFamily' || 'string' => 'String',
      final other => throw TokenException(
        '${f.token!.name}: unsupported \$type "$other"',
      ),
    };
  }

  String _lerp(_Node f) {
    final a = 'a.${f.field}';
    final b = 'b.${f.field}';
    if (f.isGroup) return '${className(f)}.lerp($a, $b, t)';
    return switch (_type(f)) {
      'Color' => 'Color.lerp($a, $b, t)!',
      'double' => 'lerpDouble($a, $b, t)!',
      'TextStyle' => 'TextStyle.lerp($a, $b, t)!',
      'List<BoxShadow>' => 'BoxShadow.lerpList($a, $b, t)!',
      'FontWeight' => 'FontWeight.lerp($a, $b, t)!',
      _ => 't < 0.5 ? $a : $b',
    };
  }

  String _value(DesignToken token, _Variant variant) {
    final where = '${token.name} (${variant.mode})';
    final raw = variant.reduced && token.reducedMotion != null
        ? set.resolveValue(token.reducedMotion, variant.mode, owner: token.name)
        : set.resolve(token.name, variant.mode);
    switch (token.type) {
      case 'color':
        return TokenColor.parse(raw, where).dart;
      case 'dimension':
        return dartNum(parseDimension(raw, where));
      case 'number':
        return dartNum(parseNumber(raw, where));
      case 'duration':
        return dartDuration(parseDurationMicros(raw, where));
      case 'cubicBezier':
        return 'Cubic(${parseCubicBezier(raw, where).map(dartNum).join(', ')})';
      case 'shadow':
        final layers = parseShadow(raw, where);
        return '<BoxShadow>[${layers.map((l) => l.dart).join(', ')}]';
      case 'fontWeight':
        return 'FontWeight.w${parseFontWeight(raw, where)}';
      case 'fontFamily' || 'string':
        if (raw is! String) throw TokenException('$where: must be a string');
        return _string(raw);
      case 'typography':
        return _textStyle(token, raw, variant.mode, where);
      default:
        throw TokenException('$where: unsupported \$type "${token.type}"');
    }
  }

  String _textStyle(DesignToken token, Object? raw, String mode, String where) {
    if (raw is! Map<String, Object?>) {
      throw TokenException('$where: typography must be an object');
    }
    final family = raw['fontFamily'];
    if (family is! String) {
      throw TokenException('$where: fontFamily must be a string');
    }
    final size = parseDimension(raw['fontSize'], '$where.fontSize');
    final lineHeight = parseDimension(raw['lineHeight'], '$where.lineHeight');
    final weight = parseFontWeight(raw['fontWeight'], '$where.fontWeight');
    final spacing = parseDimension(
      raw['letterSpacing'] ?? 0,
      '$where.letterSpacing',
    );
    final fallback = _fallbacks(token, family, mode);
    final package = options.fontPackage;
    return [
      'TextStyle(',
      'fontFamily: ${_string(family)}, ',
      if (fallback.isNotEmpty)
        'fontFamilyFallback: <String>[${fallback.map(_string).join(', ')}], ',
      if (package != null) 'package: ${_string(package)}, ',
      'fontSize: ${dartNum(size)}, ',
      'fontWeight: FontWeight.w$weight, ',
      'height: ${dartNum(lineHeight)} / ${dartNum(size)}, ',
      'letterSpacing: ${dartNum(spacing)}, ',
      'leadingDistribution: TextLeadingDistribution.even,',
      ')',
    ].join();
  }

  /// The other scripts' families of the font token that the role's
  /// `fontFamily` aliases (`{font.family.display.latin}` → the distinct
  /// values of `font.family.display.*` except the primary), in file order.
  List<String> _fallbacks(DesignToken token, String primary, String mode) {
    final value = token.value;
    if (value is! Map<String, Object?>) return const [];
    final target = TokenSet.aliasOf(value['fontFamily']);
    if (target == null || !target.contains('.')) return const [];
    final parent = target.substring(0, target.lastIndexOf('.'));
    final result = <String>[];
    for (final name in set.tokens.keys) {
      if (!name.startsWith('$parent.') ||
          name.substring(parent.length + 1).contains('.')) {
        continue;
      }
      final family = set.resolve(name, mode);
      if (family is String && family != primary && !result.contains(family)) {
        result.add(family);
      }
    }
    return result;
  }

  String _jsonPath(_Node node) =>
      node.tokens.first.path.take(node.fieldPath.length).join('.');
}

String _string(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

String _docLine(String text) => text.replaceAll(RegExp(r'\s+'), ' ').trim();
