import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:taro_dart_tools/content.dart';
import 'package:test/test.dart';

import 'fixture.dart';

/// Lossless WebP through the `image` package; [hugeAbove] makes every
/// encode above that quality return an over-budget blob.
final class _FakeEncoder implements ArtEncoder {
  _FakeEncoder({this.hugeAbove, this.fail = false});

  final int? hugeAbove;
  final bool fail;
  final List<int> qualities = [];

  @override
  String describe() {
    if (fail) throw const ArtEncoderException('no encoder');
    return 'fake 1.0';
  }

  @override
  Uint8List encode(img.Image image, {required int quality}) {
    qualities.add(quality);
    if (hugeAbove != null && quality > hugeAbove!) {
      return Uint8List(kArtBudgetBytes + 1);
    }
    return img.WebPEncoder().encode(image);
  }
}

final class _ThrowingEncoder extends _FakeEncoder {
  @override
  Uint8List encode(img.Image image, {required int quality}) =>
      throw const ArtEncoderException('cwebp exited 1: boom');
}

const _width = 30; // @3x width used by the fixtures: 30 × 52, @2x 20 × 34.

Uint8List _png(int w, int h) {
  final image = img.Image(width: w, height: h);
  img.fill(image, color: img.ColorRgb8(40, 30, 90));
  img.fillRect(
    image,
    x1: 2,
    y1: 2,
    x2: w ~/ 2,
    y2: h ~/ 2,
    color: img.ColorRgb8(200, 160, 90),
  );
  return img.encodePng(image);
}

/// A complete source folder (78 cards + back) of [w] × [h] PNGs.
Directory _source({int w = _width, int h = 52}) {
  final dir = Directory.systemTemp.createTempSync('taro_art_src_');
  final png = _png(w, h);
  for (final id in kCardIds) {
    File('${dir.path}/$id.png').writeAsBytesSync(png);
  }
  File('${dir.path}/back.png').writeAsBytesSync(png);
  return dir;
}

const _pubspec = '''
flutter:
  assets:
    # Generated by tools/content build.
    - assets/deck/
    - assets/deck/art/placeholder/
''';

/// A minimal repository: specs marker, the real tokens, deck.yaml, pubspec.
Directory _repo() {
  final root = Directory.systemTemp.createTempSync('taro_art_repo_');
  Directory('${root.path}/docs/specs').createSync(recursive: true);
  File('${root.path}/$kTokensPath')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
      File('${realRepo.path}/$kTokensPath').readAsStringSync(),
    );
  File('${root.path}/$kDeckYamlPath')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(
      '# deck\nid: rws_original\nversion: 1\n'
      'artSet: placeholder\n',
    );
  File('${root.path}/$kAppPubspecPath')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(_pubspec);
  return root;
}

RunResult _run(
  Directory root,
  List<String> args, {
  ArtEncoder? encoder,
  Directory? cwd,
}) {
  final out = StringBuffer();
  final err = StringBuffer();
  final code = runImportArt(
    ['--repo-root', root.path, ...args],
    io: ContentIo(out: out, err: err, cwd: cwd, clock: () => fixtureToday),
    encoderFactory: (_) => encoder ?? _FakeEncoder(),
  );
  return (code: code, out: out.toString(), err: err.toString());
}

ArtImportOptions _options({int budget = kArtBudgetBytes}) => ArtImportOptions(
  artSet: 'd15',
  aspectRatio: 0.58,
  cardWidths: const {'thumb': 40, 'lg': 220},
  width3x: _width,
  budgetBytes: budget,
);

void main() {
  final temps = <Directory>[];
  Directory track(Directory d) {
    temps.add(d);
    return d;
  }

  tearDown(() {
    for (final d in temps) {
      if (d.existsSync()) d.deleteSync(recursive: true);
    }
    temps.clear();
  });

  group('tokens', () {
    test('reads size.card from the real tokens', () {
      final t = readCardSizeTokens(realRepo);
      expect(t.aspectRatio, 0.58);
      expect(t.widths, {'thumb': 40, 'sm': 72, 'md': 104, 'lg': 220});
    });

    test('missing, malformed and incomplete tokens throw', () {
      final root = track(Directory.systemTemp.createTempSync('taro_tok_'));
      final file = File('${root.path}/$kTokensPath');
      expect(
        () => readCardSizeTokens(root),
        throwsA(isA<ContentFormatException>()),
      );
      file
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('{');
      expect(
        () => readCardSizeTokens(root),
        throwsA(isA<ContentFormatException>()),
      );
      file.writeAsStringSync('{"size": {}}');
      expect(
        () => readCardSizeTokens(root),
        throwsA(isA<ContentFormatException>()),
      );
      file.writeAsStringSync(
        r'{"size": {"card": {"aspectRatio": {"$value": "x"}}}}',
      );
      expect(
        () => readCardSizeTokens(root),
        throwsA(isA<ContentFormatException>()),
      );
      file.writeAsStringSync(
        r'{"size": {"card": {"aspectRatio": {"$value": 0.5}, '
        r'"lg": {"$value": 100}, "note": "x"}}}',
      );
      final tokens = readCardSizeTokens(root);
      expect(tokens.aspectRatio, 0.5);
      expect(tokens.widths, {'lg': 100});
    });
  });

  group('helpers', () {
    test('art keys, paths and sizes', () {
      expect(artKeyOfStem('back'), kCardBackKey);
      expect(artKeyOfStem('major_00'), 'major_00');
      expect(artKeyOfStem('card_back'), isNull);
      expect(
        artMainPath('d15', 'cups_01'),
        'apps/taro/assets/deck/art/d15/cups_01.webp',
      );
      expect(
        art3xPath('d15', 'cups_01'),
        'apps/taro/assets/deck/art/d15/3.0x/cups_01.webp',
      );
      const o = ArtImportOptions(artSet: 'd15', aspectRatio: 0.58);
      expect(o.size3x, (660, 1138));
      expect(o.size2x, (440, 759));
    });

    test('aspect ratio check and centre crop', () {
      expect(aspectMatches(58, 100, 0.58, 0.01), isTrue);
      expect(aspectMatches(60, 100, 0.58, 0.01), isFalse);
      expect(aspectMatches(60, 100, 0.58, 0.04), isTrue);
      expect(aspectMatches(1, 0, 0.58, 1), isFalse);
      final wide = cropToAspect(img.Image(width: 100, height: 100), 0.5);
      expect((wide.width, wide.height), (50, 100));
      final tall = cropToAspect(img.Image(width: 50, height: 200), 0.5);
      expect((tall.width, tall.height), (50, 100));
    });

    test('cacheWidth hints are capped at the @3x width', () {
      expect(cacheWidthHints(_options()), {
        'thumb': {'2': 30, '3': 30},
        'lg': {'2': 30, '3': 30},
      });
      expect(
        cacheWidthHints(
          const ArtImportOptions(
            artSet: 'd15',
            aspectRatio: 0.58,
            cardWidths: {'thumb': 40, 'lg': 220},
          ),
        ),
        {
          'thumb': {'2': 80, '3': 120},
          'lg': {'2': 440, '3': 660},
        },
      );
    });

    test('withArtSet replaces or appends the key', () {
      expect(
        withArtSet('# c\nid: x\nartSet: placeholder\n', 'd15'),
        '# c\nid: x\nartSet: d15\n',
      );
      expect(withArtSet('id: x', 'd15'), 'id: x\nartSet: d15\n');
      expect(withArtSet('', 'd15'), 'artSet: d15\n');
    });

    test('withArtAsset adds the entry once', () {
      final once = withArtAsset(_pubspec, 'd15');
      expect(
        once,
        contains(
          '    - assets/deck/art/placeholder/\n    - assets/deck/art/d15/',
        ),
      );
      expect(withArtAsset(once, 'd15'), once);
      expect(
        () => withArtAsset('flutter:\n', 'd15'),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });

  group('scanArtSource', () {
    test('reports a missing folder', () {
      final errors = <String>[];
      expect(scanArtSource(Directory('/nonexistent/taro'), errors), isEmpty);
      expect(errors.single, contains('does not exist'));
    });

    test('reports strays, duplicates and missing keys; ignores dotfiles', () {
      final dir = track(_source());
      File('${dir.path}/major_00.png').deleteSync();
      File('${dir.path}/back.jpg').writeAsBytesSync([1]);
      File('${dir.path}/notes.txt').writeAsStringSync('x');
      File('${dir.path}/README').writeAsStringSync('x');
      File('${dir.path}/.DS_Store').writeAsStringSync('x');
      final errors = <String>[];
      final found = scanArtSource(dir, errors);
      expect(found, hasLength(78));
      expect(errors, [
        'README: not a card ID or "back" with png/jpg/jpeg/webp',
        'back.png: second file for card_back',
        'notes.txt: not a card ID or "back" with png/jpg/jpeg/webp',
        'major_00: missing',
      ]);
    });

    test('names the back by its source stem when missing', () {
      final dir = track(_source());
      File('${dir.path}/back.png').deleteSync();
      final errors = <String>[];
      scanArtSource(dir, errors);
      expect(errors, ['back: missing']);
    });
  });

  group('planArtImport', () {
    test('converts the set and writes a manifest', () {
      final encoder = _FakeEncoder();
      final lines = <String>[];
      final plan = planArtImport(
        track(_source()),
        _options(),
        encoder,
        log: lines.add,
      );
      expect(plan.errors, isEmpty);
      expect(plan.files, hasLength(79 * 2 + 1));
      expect(lines, hasLength(79));
      final x3 = img.decodeWebP(plan.files[art3xPath('d15', 'major_00')]!)!;
      expect((x3.width, x3.height), (30, 52));
      final x2 = img.decodeWebP(plan.files[artMainPath('d15', 'card_back')]!)!;
      expect((x2.width, x2.height), (20, 34));
      final manifest =
          jsonDecode(
                utf8.decode(
                  plan.files['apps/taro/assets/deck/art/d15/art_manifest.json']!,
                ),
              )
              as Map<String, Object?>;
      expect(manifest['artSet'], 'd15');
      expect(manifest['encoder'], 'fake 1.0');
      expect(
        (manifest['files']! as Map)['card_back'],
        containsPair(
          'quality',
          90,
        ),
      );
      expect(manifest['densities'], {
        '2x': {'width': 20, 'height': 34, 'path': '<artKey>.webp'},
        '3x': {'width': 30, 'height': 52, 'path': '3.0x/<artKey>.webp'},
      });
      expect(manifest['totalBytes'], isPositive);
    });

    test('steps the quality down until @3x fits', () {
      final encoder = _FakeEncoder(hugeAbove: 75);
      final plan = planArtImport(track(_source()), _options(), encoder);
      expect(plan.errors, isEmpty);
      expect(encoder.qualities.take(5), [90, 85, 80, 75, 75]);
    });

    test('goes below quality 60 for dense art', () {
      final encoder = _FakeEncoder(hugeAbove: 45);
      final plan = planArtImport(track(_source()), _options(), encoder);
      expect(plan.errors, isEmpty);
      expect(encoder.qualities.take(10), [
        90,
        85,
        80,
        75,
        70,
        65,
        60,
        55,
        50,
        45,
      ]);
    });

    test('fails when even the lowest quality is over budget', () {
      final plan = planArtImport(
        track(_source()),
        _options(),
        _FakeEncoder(hugeAbove: 0),
      );
      expect(plan.files, isEmpty);
      expect(plan.errors, hasLength(79));
      expect(plan.errors.first, contains('at quality 40'));
    });

    test('an unavailable encoder stops before reading the source', () {
      final plan = planArtImport(
        Directory('/nonexistent'),
        _options(),
        _FakeEncoder(fail: true),
      );
      expect(plan.errors, ['encoder: no encoder']);
    });

    test('rejects undecodable, off-ratio and too small images', () {
      final dir = track(_source());
      File('${dir.path}/major_01.png').writeAsBytesSync([1, 2, 3]);
      File('${dir.path}/major_02.png').writeAsBytesSync(_png(30, 30));
      File('${dir.path}/major_03.png').writeAsBytesSync(_png(29, 50));
      final plan = planArtImport(dir, _options(), _FakeEncoder());
      expect(plan.files, isEmpty);
      expect(plan.errors, [
        'major_01.png: not a decodable image',
        'major_02.png: 30×30 is not size.card.aspectRatio 0.58 (±2.0 %)',
        'major_03.png: 29 px wide; @3x needs at least 30 px',
      ]);
    });
  });

  group('CwebpEncoder', () {
    ProcessResult ok(String out) => ProcessResult(0, 0, out, '');

    test('describe reports the version or a missing binary', () {
      expect(
        CwebpEncoder(run: (_, _) => ok('1.5.0\n')).describe(),
        'cwebp 1.5.0',
      );
      expect(
        () =>
            CwebpEncoder(run: (_, _) => ProcessResult(0, 2, '', '')).describe(),
        throwsA(isA<ArtEncoderException>()),
      );
      expect(
        () => CwebpEncoder(
          executable: 'nope',
          run: (e, a) => throw ProcessException(e, a, 'not found'),
        ).describe(),
        throwsA(predicate((e) => '$e'.contains('brew install webp'))),
      );
    });

    test('encode passes the quality and reads the output', () {
      late List<String> seen;
      final encoder = CwebpEncoder(
        run: (_, args) {
          seen = args;
          File(args[args.indexOf('-o') + 1]).writeAsBytesSync([7, 7]);
          return ok('');
        },
      );
      expect(encoder.encode(img.Image(width: 2, height: 2), quality: 80), [
        7,
        7,
      ]);
      expect(seen.sublist(0, 3), ['-quiet', '-q', '80']);
    });

    test('encode fails on a non-zero exit', () {
      final encoder = CwebpEncoder(
        run: (_, _) => ProcessResult(0, 1, '', 'bad input\n'),
      );
      expect(
        () => encoder.encode(img.Image(width: 2, height: 2), quality: 80),
        throwsA(predicate((e) => '$e' == 'cwebp exited 1: bad input')),
      );
    });

    final hasCwebp = () {
      try {
        return Process.runSync('cwebp', ['-version']).exitCode == 0;
      } on ProcessException {
        return false;
      }
    }();

    test(
      'the real cwebp writes lossy WebP of the right size',
      () {
        final encoder = CwebpEncoder();
        expect(encoder.describe(), startsWith('cwebp '));
        final image = img.Image(width: 60, height: 103);
        img.fill(image, color: img.ColorRgb8(120, 80, 200));
        final bytes = encoder.encode(image, quality: 80);
        final decoded = img.decodeWebP(bytes)!;
        expect((decoded.width, decoded.height), (60, 103));
      },
      skip: hasCwebp ? false : 'cwebp not installed (brew install webp)',
    );
  });

  group('runImportArt', () {
    test('help and usage errors', () {
      final root = track(_repo());
      expect(_run(root, ['--help']).out, contains('import_art'));
      expect(_run(root, ['--width', 'x']).code, 64);
      expect(_run(root, ['--aspect-tolerance', '-1']).code, 64);
      expect(_run(root, ['--art-set', 'd15']).code, 64);
      expect(_run(root, ['--source', 'x']).code, 64);
      final bad = _run(root, ['--source', 'x', '--art-set', 'placeholder']);
      expect(bad.code, 64);
      expect(bad.err, contains('not placeholder'));
      expect(_run(root, ['--source', 'x', '--art-set', 'Bad-Set']).code, 64);
    });

    test('fails without a repository root or tokens', () {
      final empty = track(Directory.systemTemp.createTempSync('taro_none_'));
      final out = StringBuffer();
      final err = StringBuffer();
      expect(
        runImportArt(
          ['--check'],
          io: ContentIo(out: out, err: err, cwd: empty),
        ),
        1,
      );
      final root = track(_repo());
      File('${root.path}/$kTokensPath').deleteSync();
      expect(_run(root, ['--check']).err, contains(kTokensPath));
    });

    test('imports, updates deck.yaml and pubspec, and is idempotent', () {
      final root = track(_repo());
      final src = track(_source());
      final args = [
        '--source',
        src.path,
        '--art-set',
        'd15',
        '--width',
        '$_width',
        '--no-build',
      ];
      final first = _run(root, args);
      expect(first.code, 0, reason: first.err);
      expect(first.out, contains('159 file(s)'));
      expect(first.out, contains('159 written, 0 deleted'));
      expect(
        File('${root.path}/$kDeckYamlPath').readAsStringSync(),
        contains('artSet: d15'),
      );
      expect(
        File('${root.path}/$kAppPubspecPath').readAsStringSync(),
        contains('- assets/deck/art/d15/'),
      );

      final stray = File('${root.path}/${artSetDir('d15')}/old.webp')
        ..writeAsBytesSync([1]);
      final second = _run(root, args);
      expect(second.out, contains('0 written, 1 deleted'));
      expect(stray.existsSync(), isFalse);

      final check = _run(root, ['--check', '--width', '$_width']);
      expect(check.code, 0, reason: check.err);
      expect(check.out, contains('art set d15 OK'));
    });

    test('a relative --source resolves against the working directory', () {
      final root = track(_repo());
      final src = track(_source());
      final r = _run(
        root,
        [
          '--source',
          src.uri.pathSegments.where((s) => s.isNotEmpty).last,
          '--art-set',
          'd15',
          '--width',
          '$_width',
          '--no-build',
        ],
        cwd: src.parent,
      );
      expect(r.code, 0, reason: r.err);
    });

    test('the default encoder is cwebp at --cwebp', () {
      final root = track(_repo());
      final err = StringBuffer();
      final code = runImportArt(
        [
          '--repo-root',
          root.path,
          '--source',
          root.path,
          '--art-set',
          'd15',
          '--cwebp',
          '/nonexistent/cwebp',
        ],
        io: ContentIo(out: StringBuffer(), err: err),
      );
      expect(code, 1);
      expect('$err', contains('encoder: /nonexistent/cwebp not runnable'));
    });

    test('problems and encoder failures write nothing', () {
      final root = track(_repo());
      final src = track(_source());
      File('${src.path}/major_00.png').deleteSync();
      final base = ['--art-set', 'd15', '--width', '$_width', '--no-build'];
      final r = _run(root, ['--source', src.path, ...base]);
      expect(r.code, 1);
      expect(r.err, contains('1 problem(s); nothing written'));
      expect(
        Directory('${root.path}/${artSetDir('d15')}').existsSync(),
        isFalse,
      );

      final full = track(_source());
      final thrown = _run(root, [
        '--source',
        full.path,
        ...base,
      ], encoder: _ThrowingEncoder());
      expect(thrown.code, 1);
      expect(thrown.err, contains('boom'));
    });

    test('fails when deck.yaml is missing or the pubspec has no art entry', () {
      final root = track(_repo());
      final src = track(_source());
      final args = [
        '--source',
        src.path,
        '--art-set',
        'd15',
        '--width',
        '$_width',
        '--no-build',
      ];
      File('${root.path}/$kAppPubspecPath').writeAsStringSync('flutter:\n');
      expect(_run(root, args).err, contains('no "- assets/deck/art/" entry'));
      File('${root.path}/$kDeckYamlPath').deleteSync();
      expect(_run(root, args).code, 1);
      expect(_run(root, ['--check']).code, 1);
    });

    test('runs the content build, which carries artSet into deck_meta', () {
      final repo = FixtureRepo.create();
      addTearDown(repo.dispose);
      File('${repo.root.path}/$kTokensPath')
        ..parent.createSync(recursive: true)
        ..writeAsStringSync(
          File('${realRepo.path}/$kTokensPath').readAsStringSync(),
        );
      final src = track(_source());
      final r = _run(repo.root, [
        '--source',
        src.path,
        '--art-set',
        'd15',
        '--width',
        '$_width',
      ]);
      expect(r.code, 0, reason: r.err);
      expect(r.out, contains('content build:'));
      final meta = jsonDecode(repo.read(kDeckMetaPath)) as Map;
      expect(meta['artSet'], 'd15');
    });
  });

  group('checkArtSet', () {
    Directory imported() {
      final root = track(_repo());
      final src = track(_source());
      expect(
        _run(root, [
          '--source',
          src.path,
          '--art-set',
          'd15',
          '--width',
          '$_width',
          '--no-build',
        ]).code,
        0,
      );
      return root;
    }

    List<String> check(Directory root, [String set = 'd15']) =>
        checkArtSet(root, set, aspectRatio: 0.58);

    test('an empty set has no art', () {
      expect(check(track(_repo())).single, contains('no art'));
    });

    test('the placeholder set only needs its main files', () {
      final root = track(_repo());
      for (final key in placeholderArtKeys()) {
        File('${root.path}/${artMainPath('placeholder', key)}')
          ..parent.createSync(recursive: true)
          ..writeAsBytesSync([1, 2]);
      }
      expect(check(root, 'placeholder'), isEmpty);
      final r = _run(root, ['--check']);
      expect(r.out, contains('art set placeholder OK'));
    });

    test('finds missing, stray, oversize, non-WebP and off-ratio files', () {
      final root = imported();
      String p(String rel) => '${root.path}/$rel';
      File(p(art3xPath('d15', 'major_00'))).deleteSync();
      File(p('${artSetDir('d15')}/extra.webp')).writeAsBytesSync([1]);
      File(
        p(artMainPath('d15', 'major_01')),
      ).writeAsBytesSync(Uint8List(kArtBudgetBytes + 1));
      File(p(art3xPath('d15', 'major_02'))).writeAsBytesSync(
        img.WebPEncoder().encode(img.Image(width: 30, height: 30)),
      );
      File(p('${artSetDir('d15')}/$kArtManifestName')).deleteSync();
      File(p(kAppPubspecPath)).writeAsStringSync(_pubspec);
      final problems = check(root);
      expect(problems, [
        'apps/taro/assets/deck/art/d15/3.0x/major_00.webp: missing',
        'apps/taro/assets/deck/art/d15/3.0x/major_02.webp: 30×30 is not 0.58',
        'apps/taro/assets/deck/art/d15/art_manifest.json: missing',
        'apps/taro/assets/deck/art/d15/extra.webp: not part of the art set',
        'apps/taro/assets/deck/art/d15/major_01.webp: 150001 bytes > budget 150000',
        'apps/taro/assets/deck/art/d15/major_01.webp: not a WebP file',
        'apps/taro/pubspec.yaml: no "- assets/deck/art/d15/" entry',
      ]);
      final r = _run(root, ['--check', '--art-set', 'd15']);
      expect(r.code, 1);
      expect(r.err, contains('7 problem(s)'));
    });
  });
}
