// GENERATED by tools/screenshots/screenshots.py fixtures — do not edit.
// Source: apps/taro/test/fixtures/store_readings/{locale}.json.

/// The store reading fixtures (05 §9.4) as JSON, by locale.
const Map<String, String> kStoreReadingsJson = {
  'en': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "en",
  "question": "How can I bring more balance into my week?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Room to breathe",
    "overview": "The cards move from warm connection, through a quiet return of hope, toward a small and practical new start. Together they suggest that balance may grow from simple choices you make on purpose.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "In the past position, the Three of Cups recalls times when friends and shared moments kept you steady. A meal together, laughter or a message from someone close may have given your weeks a natural rhythm. It may help to ask which of those connections you would like to make room for again."
      },
      {
        "positionId": "present",
        "interpretation": "The Star in the present position speaks of calm and renewed hope after a busy stretch. It invites you to slow down and notice what quietly refills your energy, such as rest, fresh air or a moment of stillness. You might treat these not as rewards, but as part of the week itself."
      },
      {
        "positionId": "future",
        "interpretation": "In the future position, the Ace of Pentacles points to a small, practical beginning that you can choose. This could be one steady habit: a regular walk, a set time to switch off, or a simple plan for the days ahead. It is less about a big change and more about a seed you can tend."
      }
    ],
    "synthesis": "Read together, the cards suggest that balance may come from mixing connection, rest and one grounded routine. You decide which step feels right; the spread simply offers a few angles to reflect on.",
    "reflectionPrompts": [
      "Which moments in your week leave you feeling most like yourself?",
      "What is one small habit you could try for the next seven days?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "What do I value most in my friendships?",
      "title": "The gift of being heard",
      "overview": "The Two of Cups highlights mutual care and the quiet strength of being listened to."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "How can I approach my new project?",
      "title": "Steady, curious steps",
      "overview": "The cards point from planning, through creativity, toward patient practice."
    }
  ]
}''',
  'ar': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "ar",
  "question": "كيف أضيف مزيدًا من التوازن إلى أسبوعي؟",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "مساحة لالتقاط الأنفاس",
    "overview": "تنتقل البطاقات من الصلة الدافئة بالآخرين، مرورًا بعودة هادئة للأمل، نحو بداية صغيرة وعملية. ومعًا تشير إلى أن التوازن قد ينمو من خيارات بسيطة تتخذها عن قصد.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "في موضع الماضي، تُذكّرك ثلاثة من الكؤوس بأوقات منحتك فيها الصداقة واللحظات المشتركة شعورًا بالثبات. ربما أعطت وجبة مع الأصدقاء أو ضحكة أو رسالة من شخص قريب أسابيعك إيقاعًا طبيعيًا. قد يفيدك أن تسأل نفسك: أيّ هذه الروابط تودّ أن تفسح لها المجال من جديد؟"
      },
      {
        "positionId": "present",
        "interpretation": "النجمة في موضع الحاضر تتحدث عن الهدوء وعن أمل يتجدد بعد فترة مزدحمة. إنها تدعوك إلى التمهّل وملاحظة ما يعيد إليك طاقتك بهدوء، مثل الراحة أو الهواء الطلق أو لحظة سكون. يمكنك أن تعدّ هذه اللحظات جزءًا من أسبوعك، لا مكافأة عليه."
      },
      {
        "positionId": "future",
        "interpretation": "في موضع المستقبل، يشير آس العملات إلى بداية صغيرة وعملية يمكنك أن تختارها بنفسك. قد تكون عادة ثابتة واحدة: نزهة منتظمة، أو وقتًا محددًا للابتعاد عن الشاشات، أو خطة بسيطة للأيام القادمة. الأمر أقرب إلى بذرة ترعاها منه إلى تغيير كبير."
      }
    ],
    "synthesis": "حين تُقرأ البطاقات معًا، توحي بأن التوازن قد يأتي من الجمع بين الصلة بالآخرين والراحة وعادة ثابتة واحدة. أنت من يقرر أيّ خطوة تناسبك؛ فالفرشة تقدّم لك فقط زوايا للتأمل.",
    "reflectionPrompts": [
      "في أيّ لحظات من أسبوعك تشعر بأنك أقرب إلى نفسك؟",
      "ما العادة الصغيرة التي يمكنك تجربتها خلال الأيام السبعة القادمة؟"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "ما أكثر ما أقدّره في صداقاتي؟",
      "title": "هدية أن يُصغى إليك",
      "overview": "يُبرز اثنان من الكؤوس الاهتمام المتبادل وقوة الإصغاء الهادئة."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "كيف أبدأ مشروعي الجديد؟",
      "title": "خطوات هادئة وفضولية",
      "overview": "تنتقل البطاقات من التخطيط إلى الإبداع ثم إلى الممارسة الصبورة."
    }
  ]
}''',
  'de': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "de",
  "question": "Wie bringe ich mehr Ausgleich in meine Woche?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Raum zum Durchatmen",
    "overview": "Die Karten führen von herzlicher Verbundenheit über eine leise zurückkehrende Hoffnung zu einem kleinen, praktischen Neuanfang. Zusammen deuten sie an, dass Ausgleich aus einfachen, bewusst getroffenen Entscheidungen wachsen kann.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "In der Position der Vergangenheit erinnert die Drei der Kelche an Zeiten, in denen Freundschaften und gemeinsame Momente dir Halt gaben. Ein gemeinsames Essen, Lachen oder eine Nachricht von einem vertrauten Menschen hat deinen Wochen vielleicht einen natürlichen Rhythmus gegeben. Frag dich, für welche dieser Verbindungen du wieder Platz schaffen möchtest."
      },
      {
        "positionId": "present",
        "interpretation": "Der Stern in der Gegenwart spricht von Ruhe und neuer Hoffnung nach einer vollen Zeit. Er lädt dich ein, langsamer zu werden und zu bemerken, was dir leise Kraft zurückgibt: Pausen, frische Luft oder ein Moment der Stille. Vielleicht siehst du diese Dinge nicht als Belohnung, sondern als festen Teil deiner Woche."
      },
      {
        "positionId": "future",
        "interpretation": "In der Position der Zukunft zeigt das Ass der Münzen auf einen kleinen, praktischen Anfang, den du selbst wählen kannst. Das kann eine einzige verlässliche Gewohnheit sein: ein regelmäßiger Spaziergang, eine feste Zeit zum Abschalten oder ein einfacher Plan für die kommenden Tage. Es geht weniger um eine große Veränderung als um einen Samen, den du pflegen kannst."
      }
    ],
    "synthesis": "Zusammen gelesen legen die Karten nahe, dass Ausgleich aus Verbundenheit, Ruhe und einer geerdeten Routine entstehen kann. Welcher Schritt sich richtig anfühlt, entscheidest du; die Legung bietet dir nur ein paar Blickwinkel zum Nachdenken.",
    "reflectionPrompts": [
      "In welchen Momenten deiner Woche fühlst du dich am meisten wie du selbst?",
      "Welche kleine Gewohnheit könntest du die nächsten sieben Tage ausprobieren?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Was schätze ich an meinen Freundschaften am meisten?",
      "title": "Das Geschenk, gehört zu werden",
      "overview": "Die Zwei der Kelche betont gegenseitige Fürsorge und die stille Kraft des Zuhörens."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Wie gehe ich mein neues Projekt an?",
      "title": "Ruhige, neugierige Schritte",
      "overview": "Die Karten führen von der Planung über Kreativität zu geduldiger Übung."
    }
  ]
}''',
  'es': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "es",
  "question": "¿Cómo puedo traer más equilibrio a mi semana?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Espacio para respirar",
    "overview": "Las cartas van de una conexión cálida, pasando por un regreso sereno de la esperanza, hacia un comienzo pequeño y práctico. Juntas sugieren que el equilibrio puede crecer a partir de decisiones sencillas que tomas a propósito.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "En la posición del pasado, el Tres de Copas recuerda momentos en que la amistad y los ratos compartidos te daban estabilidad. Una comida juntos, unas risas o un mensaje de alguien cercano quizá daban a tus semanas un ritmo natural. Puede ayudarte preguntarte a cuáles de esas conexiones te gustaría volver a hacer sitio."
      },
      {
        "positionId": "present",
        "interpretation": "La Estrella en la posición del presente habla de calma y de una esperanza renovada después de una etapa intensa. Te invita a ir más despacio y a notar qué te devuelve la energía en silencio: descansar, el aire libre o un momento de quietud. Quizá puedas verlo no como un premio, sino como parte de la propia semana."
      },
      {
        "positionId": "future",
        "interpretation": "En la posición del futuro, el As de Oros señala un comienzo pequeño y práctico que tú puedes elegir. Podría ser un solo hábito constante: un paseo regular, una hora fija para desconectar o un plan sencillo para los próximos días. Se trata menos de un gran cambio y más de una semilla que puedes cuidar."
      }
    ],
    "synthesis": "Leídas en conjunto, las cartas sugieren que el equilibrio puede surgir de combinar conexión, descanso y una rutina con los pies en la tierra. Tú decides qué paso te parece adecuado; la tirada solo te ofrece algunos ángulos para reflexionar.",
    "reflectionPrompts": [
      "¿Qué momentos de tu semana te hacen sentir más tú?",
      "¿Qué pequeño hábito podrías probar durante los próximos siete días?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "¿Qué es lo que más valoro de mis amistades?",
      "title": "El regalo de sentirse escuchado",
      "overview": "El Dos de Copas destaca el cuidado mutuo y la fuerza tranquila de ser escuchado."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "¿Cómo puedo abordar mi nuevo proyecto?",
      "title": "Pasos firmes y curiosos",
      "overview": "Las cartas van de la planificación a la creatividad y a la práctica paciente."
    }
  ]
}''',
  'fr': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "fr",
  "question": "Comment apporter plus d’équilibre à ma semaine ?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "De l’espace pour respirer",
    "overview": "Les cartes vont d’un lien chaleureux, en passant par un retour paisible de l’espoir, vers un petit commencement concret. Ensemble, elles suggèrent que l’équilibre peut naître de choix simples que vous faites en conscience.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "En position du passé, le Trois de Coupes rappelle des moments où l’amitié et les instants partagés vous donnaient de la stabilité. Un repas ensemble, des rires ou un message d’un proche ont peut-être donné à vos semaines un rythme naturel. Demandez-vous à quels liens vous aimeriez refaire de la place."
      },
      {
        "positionId": "present",
        "interpretation": "L’Étoile en position du présent parle de calme et d’un espoir renouvelé après une période chargée. Elle vous invite à ralentir et à remarquer ce qui recharge doucement votre énergie : le repos, l’air frais ou un moment de silence. Vous pourriez les voir non comme des récompenses, mais comme une partie de la semaine elle-même."
      },
      {
        "positionId": "future",
        "interpretation": "En position du futur, l’As de Deniers évoque un petit commencement concret que vous pouvez choisir. Ce pourrait être une seule habitude régulière : une promenade, une heure fixe pour déconnecter ou un plan simple pour les jours qui viennent. Il s’agit moins d’un grand changement que d’une graine dont vous pouvez prendre soin."
      }
    ],
    "synthesis": "Lues ensemble, les cartes suggèrent que l’équilibre peut venir d’un mélange de lien, de repos et d’une routine ancrée. C’est vous qui choisissez le pas qui vous convient ; le tirage vous offre simplement quelques angles de réflexion.",
    "reflectionPrompts": [
      "Quels moments de votre semaine vous font le plus vous sentir vous-même ?",
      "Quelle petite habitude pourriez-vous essayer pendant les sept prochains jours ?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Qu’est-ce que j’apprécie le plus dans mes amitiés ?",
      "title": "Le cadeau d’être écouté",
      "overview": "Le Deux de Coupes met en lumière l’attention mutuelle et la force tranquille de l’écoute."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Comment aborder mon nouveau projet ?",
      "title": "Des pas sûrs et curieux",
      "overview": "Les cartes vont de la planification à la créativité, puis à la pratique patiente."
    }
  ]
}''',
  'it': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "it",
  "question": "Come posso portare più equilibrio nella mia settimana?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Spazio per respirare",
    "overview": "Le carte vanno da un legame caloroso, attraverso un ritorno sereno della speranza, verso un piccolo inizio concreto. Insieme suggeriscono che l’equilibrio può nascere da scelte semplici fatte con intenzione.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "Nella posizione del passato, il Tre di Coppe ricorda momenti in cui le amicizie e il tempo condiviso ti davano stabilità. Una cena insieme, una risata o un messaggio da una persona cara forse davano alle tue settimane un ritmo naturale. Può aiutarti chiederti per quali di questi legami vorresti fare di nuovo spazio."
      },
      {
        "positionId": "present",
        "interpretation": "La Stella nella posizione del presente parla di calma e di una speranza rinnovata dopo un periodo intenso. Ti invita a rallentare e a notare ciò che ricarica in silenzio le tue energie: il riposo, l’aria aperta o un momento di quiete. Potresti considerarli non come premi, ma come parte della settimana stessa."
      },
      {
        "positionId": "future",
        "interpretation": "Nella posizione del futuro, l’Asso di Denari indica un piccolo inizio concreto che puoi scegliere tu. Potrebbe essere una sola abitudine costante: una passeggiata regolare, un orario fisso per staccare o un piano semplice per i prossimi giorni. Non si tratta tanto di un grande cambiamento quanto di un seme di cui prenderti cura."
      }
    ],
    "synthesis": "Lette insieme, le carte suggeriscono che l’equilibrio può nascere dall’unione di legami, riposo e una routine con i piedi per terra. Sei tu a scegliere il passo giusto; la stesa offre solo alcuni punti di vista su cui riflettere.",
    "reflectionPrompts": [
      "In quali momenti della settimana ti senti più te stesso?",
      "Quale piccola abitudine potresti provare nei prossimi sette giorni?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Che cosa apprezzo di più nelle mie amicizie?",
      "title": "Il dono di essere ascoltati",
      "overview": "Il Due di Coppe mette in luce la cura reciproca e la forza tranquilla dell’ascolto."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Come posso affrontare il mio nuovo progetto?",
      "title": "Passi calmi e curiosi",
      "overview": "Le carte vanno dalla pianificazione alla creatività, fino alla pratica paziente."
    }
  ]
}''',
  'ja': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "ja",
  "question": "一週間にもっとバランスを取り入れるには？",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "ひと息つける余白",
    "overview": "カードは、温かなつながりから、静かに戻ってくる希望を経て、小さく実践的な始まりへと流れています。バランスは、自分で意識して選ぶ小さな行動から育っていくのかもしれません。",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "過去の位置にあるカップの3は、友人やともに過ごした時間があなたを支えていた頃を思い出させます。一緒の食事や笑い声、身近な人からのメッセージが、毎週に自然なリズムを与えていたのかもしれません。そうしたつながりのうち、どれにもう一度時間をつくりたいか考えてみてもよいでしょう。"
      },
      {
        "positionId": "present",
        "interpretation": "現在の位置にある星は、慌ただしい時期のあとに訪れる落ち着きと、新たな希望を表しています。ペースを落とし、休息や外の空気、静かなひとときなど、そっと力を取り戻させてくれるものに目を向けるよう促しています。それをご褒美ではなく、一週間の一部として扱ってみてはいかがでしょうか。"
      },
      {
        "positionId": "future",
        "interpretation": "未来の位置にあるペンタクルのエースは、あなた自身が選べる小さく実践的な始まりを示しています。定期的な散歩、スマホを置く時間を決めること、これからの数日のシンプルな計画など、ひとつの習慣かもしれません。大きな変化というより、育てていける一粒の種のようなものです。"
      }
    ],
    "synthesis": "三枚を合わせて読むと、つながり、休息、そして地に足のついた習慣を組み合わせることでバランスが生まれるのかもしれません。どの一歩がしっくりくるかはあなた次第です。このスプレッドは、考えるためのいくつかの視点を差し出しているだけです。",
    "reflectionPrompts": [
      "一週間のなかで、いちばん自分らしくいられるのはどんな瞬間ですか？",
      "これからの7日間で試せる小さな習慣は何でしょう？"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "友人関係でいちばん大切にしていることは？",
      "title": "耳を傾けてもらえるという贈り物",
      "overview": "カップの2は、互いを思いやる気持ちと、聴いてもらえることの静かな力を表しています。"
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "新しいプロジェクトにどう向き合えばいい？",
      "title": "落ち着いた、好奇心ある一歩",
      "overview": "カードは計画から創造性、そして根気強い実践へと続いています。"
    }
  ]
}''',
  'ko': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "ko",
  "question": "한 주에 균형을 더 가져오려면 어떻게 해야 할까요?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "숨 돌릴 여유",
    "overview": "카드는 따뜻한 관계에서 시작해 조용히 돌아오는 희망을 지나, 작고 실천적인 시작으로 이어집니다. 함께 보면 균형은 스스로 의식해서 고르는 작은 선택에서 자라날 수 있다는 점을 보여 줘요.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "과거 자리의 컵 3은 친구들과 함께한 순간들이 당신을 든든하게 받쳐 주던 때를 떠올리게 해요. 함께한 식사, 웃음, 가까운 사람의 메시지가 한 주에 자연스러운 리듬을 만들어 주었을지도 몰라요. 그중 어떤 관계에 다시 시간을 내고 싶은지 생각해 보면 도움이 될 수 있어요."
      },
      {
        "positionId": "present",
        "interpretation": "현재 자리의 별은 바쁜 시기를 지난 뒤 찾아오는 차분함과 새로워진 희망을 말해요. 속도를 늦추고 휴식, 바깥 공기, 잠깐의 고요함처럼 조용히 에너지를 채워 주는 것들을 알아차려 보라고 권해요. 이런 시간을 보상이 아니라 한 주의 일부로 여겨 볼 수도 있어요."
      },
      {
        "positionId": "future",
        "interpretation": "미래 자리의 펜타클 에이스는 당신이 직접 고를 수 있는 작고 실천적인 시작을 가리켜요. 규칙적인 산책, 화면을 끄는 정해진 시간, 앞으로 며칠을 위한 간단한 계획처럼 하나의 꾸준한 습관일 수 있어요. 큰 변화라기보다 정성껏 가꿀 수 있는 씨앗에 가까워요."
      }
    ],
    "synthesis": "세 장을 함께 읽으면, 균형은 관계와 휴식, 그리고 땅에 발을 디딘 하나의 루틴이 어우러질 때 생길 수 있다는 뜻으로 볼 수 있어요. 어떤 걸음이 맞는지는 당신이 정해요. 이 스프레드는 생각해 볼 몇 가지 관점을 건넬 뿐이에요.",
    "reflectionPrompts": [
      "한 주 중 언제 가장 나다운 기분이 드나요?",
      "앞으로 7일 동안 시도해 볼 수 있는 작은 습관은 무엇인가요?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "우정에서 내가 가장 소중히 여기는 것은?",
      "title": "귀 기울여 주는 마음이라는 선물",
      "overview": "컵 2는 서로를 아끼는 마음과 경청의 조용한 힘을 보여 줘요."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "새 프로젝트에 어떻게 다가가면 좋을까요?",
      "title": "차분하고 호기심 어린 걸음",
      "overview": "카드는 계획에서 창의성을 거쳐 꾸준한 연습으로 이어져요."
    }
  ]
}''',
  'nl': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "nl",
  "question": "Hoe breng ik meer balans in mijn week?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Ruimte om te ademen",
    "overview": "De kaarten gaan van warme verbondenheid, via een rustige terugkeer van hoop, naar een klein en praktisch nieuw begin. Samen laten ze zien dat balans kan groeien uit eenvoudige keuzes die je bewust maakt.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "Op de plek van het verleden herinnert de Drie van Kelken aan tijden waarin vriendschap en gedeelde momenten je houvast gaven. Samen eten, lachen of een berichtje van iemand dichtbij gaf je weken misschien een natuurlijk ritme. Het kan helpen om je af te vragen voor welke van die verbindingen je weer ruimte wilt maken."
      },
      {
        "positionId": "present",
        "interpretation": "De Ster op de plek van het heden spreekt over rust en hernieuwde hoop na een drukke periode. Ze nodigt je uit om te vertragen en te merken wat je stilletjes nieuwe energie geeft, zoals rust, frisse lucht of een moment van stilte. Je kunt die momenten zien als vast onderdeel van je week, niet als beloning."
      },
      {
        "positionId": "future",
        "interpretation": "Op de plek van de toekomst wijst de Aas van Pentakels op een klein, praktisch begin dat je zelf kunt kiezen. Dat kan één vaste gewoonte zijn: een regelmatige wandeling, een vast moment om uit te schakelen of een eenvoudig plan voor de komende dagen. Het gaat minder om een grote verandering en meer om een zaadje dat je kunt verzorgen."
      }
    ],
    "synthesis": "Samen gelezen suggereren de kaarten dat balans kan ontstaan uit verbondenheid, rust en één geaarde routine. Jij bepaalt welke stap goed voelt; de legging biedt je alleen een paar invalshoeken om over na te denken.",
    "reflectionPrompts": [
      "Op welke momenten in je week voel je je het meest jezelf?",
      "Welke kleine gewoonte zou je de komende zeven dagen kunnen proberen?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Wat waardeer ik het meest in mijn vriendschappen?",
      "title": "Het geschenk van gehoord worden",
      "overview": "De Twee van Kelken laat wederzijdse zorg en de stille kracht van luisteren zien."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Hoe pak ik mijn nieuwe project aan?",
      "title": "Rustige, nieuwsgierige stappen",
      "overview": "De kaarten gaan van plannen, via creativiteit, naar geduldig oefenen."
    }
  ]
}''',
  'pt': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "pt",
  "question": "Como posso trazer mais equilíbrio para a minha semana?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Espaço para respirar",
    "overview": "As cartas vão de uma conexão calorosa, passando por um retorno tranquilo da esperança, até um começo pequeno e prático. Juntas, sugerem que o equilíbrio pode nascer de escolhas simples feitas com intenção.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "Na posição do passado, o Três de Copas lembra momentos em que amizades e momentos compartilhados davam estabilidade a você. Uma refeição juntos, risadas ou uma mensagem de alguém próximo talvez dessem às suas semanas um ritmo natural. Pode ajudar perguntar a si mesmo para quais dessas conexões você gostaria de abrir espaço de novo."
      },
      {
        "positionId": "present",
        "interpretation": "A Estrela na posição do presente fala de calma e de esperança renovada depois de uma fase agitada. Ela convida você a desacelerar e perceber o que recarrega sua energia em silêncio, como descanso, ar fresco ou um momento de quietude. Você pode encarar isso não como recompensa, mas como parte da própria semana."
      },
      {
        "positionId": "future",
        "interpretation": "Na posição do futuro, o Ás de Ouros aponta para um começo pequeno e prático que você pode escolher. Pode ser um único hábito constante: uma caminhada regular, um horário fixo para desligar ou um plano simples para os próximos dias. É menos uma grande mudança e mais uma semente que você pode cultivar."
      }
    ],
    "synthesis": "Lidas em conjunto, as cartas sugerem que o equilíbrio pode vir da mistura de conexão, descanso e uma rotina com os pés no chão. Você decide qual passo faz sentido; a tiragem apenas oferece alguns ângulos para refletir.",
    "reflectionPrompts": [
      "Em quais momentos da sua semana você se sente mais você mesmo?",
      "Que pequeno hábito você poderia experimentar nos próximos sete dias?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "O que eu mais valorizo nas minhas amizades?",
      "title": "O presente de ser ouvido",
      "overview": "O Dois de Copas destaca o cuidado mútuo e a força tranquila de ser ouvido."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Como posso começar meu novo projeto?",
      "title": "Passos firmes e curiosos",
      "overview": "As cartas vão do planejamento à criatividade e à prática paciente."
    }
  ]
}''',
  'tr': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "tr",
  "question": "Haftama nasıl daha fazla denge getirebilirim?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Nefes alacak alan",
    "overview": "Kartlar sıcak bir bağdan, umudun sessizce geri dönüşünden geçerek küçük ve pratik bir başlangıca uzanıyor. Birlikte, dengenin bilinçli olarak yaptığın basit seçimlerden büyüyebileceğini düşündürüyorlar.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "Geçmiş konumundaki Kupa Üçlüsü, arkadaşlıkların ve paylaşılan anların sana güç verdiği zamanları hatırlatıyor. Birlikte yenen bir yemek, kahkahalar ya da yakın birinden gelen bir mesaj haftalarına doğal bir ritim katmış olabilir. Bu bağlardan hangilerine yeniden yer açmak istediğini kendine sormak iyi gelebilir."
      },
      {
        "positionId": "present",
        "interpretation": "Şimdi konumundaki Yıldız, yoğun bir dönemin ardından gelen sakinlikten ve yenilenen umuttan söz ediyor. Seni yavaşlamaya ve enerjini sessizce yenileyen şeyleri fark etmeye davet ediyor: dinlenmek, temiz hava ya da kısa bir sessizlik anı. Bunları bir ödül olarak değil, haftanın doğal bir parçası olarak görebilirsin."
      },
      {
        "positionId": "future",
        "interpretation": "Gelecek konumundaki Tılsım Ası, kendi seçebileceğin küçük ve pratik bir başlangıca işaret ediyor. Bu tek bir düzenli alışkanlık olabilir: düzenli bir yürüyüş, ekranları kapatmak için belirli bir saat ya da önümüzdeki günler için basit bir plan. Büyük bir değişiklikten çok, özenle büyütebileceğin bir tohum gibi."
      }
    ],
    "synthesis": "Birlikte okunduğunda kartlar, dengenin bağ kurmak, dinlenmek ve ayakları yere basan bir rutinin birleşiminden doğabileceğini düşündürüyor. Hangi adımın sana uygun olduğuna sen karar verirsin; açılım yalnızca üzerine düşünebileceğin birkaç bakış açısı sunar.",
    "reflectionPrompts": [
      "Haftanın hangi anlarında kendini en çok kendin gibi hissediyorsun?",
      "Önümüzdeki yedi gün boyunca hangi küçük alışkanlığı deneyebilirsin?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Arkadaşlıklarımda en çok neye değer veriyorum?",
      "title": "Dinlenmenin armağanı",
      "overview": "Kupa İkilisi karşılıklı özeni ve dinlenmenin sessiz gücünü öne çıkarıyor."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Yeni projeme nasıl yaklaşabilirim?",
      "title": "Sakin ve meraklı adımlar",
      "overview": "Kartlar planlamadan yaratıcılığa ve sabırlı pratiğe uzanıyor."
    }
  ]
}''',
  'uk': r'''
{
  "_about": "Store screenshot fixture (05 §9.4, Phase 20.2). The reading is the 03 §9.1 wire `reading` object for the fixed draw below, written in the style of the staging outputs and reviewed against 05 §9.5 (no predictions, no certainty claims). Read by integration_test/screenshots/ through the generated store_readings.g.dart (tools/screenshots/screenshots.py fixtures).",
  "locale": "uk",
  "question": "Як додати більше рівноваги у свій тиждень?",
  "spreadId": "three_ppf",
  "cards": [
    {
      "positionId": "past",
      "cardId": "cups_03",
      "reversed": false
    },
    {
      "positionId": "present",
      "cardId": "major_17",
      "reversed": false
    },
    {
      "positionId": "future",
      "cardId": "pentacles_01",
      "reversed": false
    }
  ],
  "reading": {
    "title": "Простір, щоб видихнути",
    "overview": "Карти ведуть від теплого зв’язку з людьми, через тихе повернення надії, до невеликого практичного початку. Разом вони підказують, що рівновага може вирости з простих рішень, які Ви ухвалюєте свідомо.",
    "cards": [
      {
        "positionId": "past",
        "interpretation": "У позиції минулого Трійка Кубків нагадує про часи, коли дружба і спільні моменти давали Вам опору. Спільна вечеря, сміх чи повідомлення від близької людини, можливо, задавали Вашим тижням природний ритм. Варто запитати себе, для яких із цих зв’язків Ви хотіли б знову знайти місце."
      },
      {
        "positionId": "present",
        "interpretation": "Зірка в позиції теперішнього говорить про спокій і відновлену надію після насиченого періоду. Вона запрошує сповільнитися й помітити, що тихо повертає Вам сили: відпочинок, свіже повітря чи хвилина тиші. Можна сприймати це не як нагороду, а як звичайну частину тижня."
      },
      {
        "positionId": "future",
        "interpretation": "У позиції майбутнього Туз Пентаклів вказує на невеликий практичний початок, який Ви можете обрати самі. Це може бути одна стала звичка: регулярна прогулянка, визначений час, щоб відключитися, або простий план на найближчі дні. Ідеться не так про великі зміни, як про зерно, яке можна плекати."
      }
    ],
    "synthesis": "Разом карти підказують, що рівновага може складатися з близькості, відпочинку й однієї заземленої звички. Ви самі вирішуєте, який крок Вам підходить; розклад лише пропонує кілька поглядів для роздумів.",
    "reflectionPrompts": [
      "У які моменти тижня Ви найбільше почуваєтеся собою?",
      "Яку маленьку звичку Ви могли б спробувати впродовж наступних семи днів?"
    ]
  },
  "dailyCardId": "major_19",
  "learnCardId": "major_21",
  "journal": [
    {
      "spreadId": "single",
      "cards": [
        "cups_02"
      ],
      "daysAgo": 2,
      "question": "Що я найбільше ціную у своїх дружніх стосунках?",
      "title": "Дар бути почутим",
      "overview": "Двійка Кубків підкреслює взаємну турботу і тиху силу того, що тебе слухають."
    },
    {
      "spreadId": "three_sao",
      "cards": [
        "wands_03",
        "major_03",
        "pentacles_08"
      ],
      "daysAgo": 5,
      "question": "Як підійти до мого нового проєкту?",
      "title": "Спокійні, допитливі кроки",
      "overview": "Карти ведуть від планування через творчість до терплячої практики."
    }
  ]
}''',
};
