import 'dart:convert';
import 'dart:io';

import 'package:taro_dart_tools/tokens.dart';
import 'package:test/test.dart';

TokenSet _fixture(String name) => TokenSet.parse(
  jsonDecode(File('test/fixtures/tokens/$name').readAsStringSync()),
);

TokenSet _set(Map<String, Object?> body) => TokenSet.parse({
  r'$extensions': {
    'taro.modes': ['light', 'dark'],
  },
  ...body,
});

void main() {
  group('the pass fixture', () {
    late String source;
    setUpAll(() {
      source = emitTokensDart(
        _fixture('pass.tokens.json'),
        options: const EmitOptions(source: 'fixture.json', fontPackage: 'ui'),
      );
    });

    test('has a header, names and modes', () {
      expect(source, startsWith('// GENERATED by tools/tokens/generate.dart'));
      expect(source, contains('from fixture.json.'));
      expect(source, contains("'color.bg.canvas',"));
      expect(source, contains('const List<String> kTaroTokenModes'));
    });

    test('emits one class per group with light, dark and lerp', () {
      expect(source, contains('final class TaroColorTokens {'));
      expect(source, contains('final class TaroColorBgTokens {'));
      expect(
        source,
        contains('static const TaroColorTokens light = TaroColorTokens('),
      );
      expect(
        source,
        contains('static const TaroColorTokens dark = TaroColorTokens('),
      );
      expect(source, contains('Color.lerp(a.canvas, b.canvas, t)!'));
      expect(source, contains('TaroColorBgTokens.lerp(a.bg, b.bg, t)'));
      expect(source, contains('/// Canvas.'));
    });

    test('mode-invariant groups alias dark to light', () {
      expect(source, contains('static const TaroSpaceTokens dark = light;'));
      expect(source, contains('s0: 0'));
      expect(source, contains('s4: 12'));
      expect(source, contains('lerpDouble(a.s4, b.s4, t)!'));
    });

    test('an aliased colour follows its target per mode', () {
      expect(source, contains('link: Color(0xFF111111)'));
      expect(source, contains('link: Color(0xFFEEEEEE)'));
    });

    test('shadows, overlays and numeric keys', () {
      expect(source, contains('final class TaroElevationE1Tokens {'));
      expect(source, contains('shadow: <BoxShadow>[]'));
      expect(source, contains('spreadRadius: 1'));
      expect(source, contains('BoxShadow.lerpList(a.shadow, b.shadow, t)!'));
      expect(source, contains('overlay: 0.03'));
    });

    test('motion has a reduced instance', () {
      expect(source, contains('static const TaroMotionTokens reduced'));
      expect(source, contains('fast: Duration(milliseconds: 150)'));
      expect(source, contains('fast: Duration(milliseconds: 0)'));
      expect(source, contains('standard: Cubic(0.2, 0, 0, 1)'));
      expect(source, contains('standard: Cubic(0, 0, 1, 1)'));
      expect(source, contains('t < 0.5 ? a.fast : b.fast'));
    });

    test('typography resolves the family and the script fallbacks', () {
      expect(source, contains("fontFamily: 'Sans'"));
      expect(source, contains("fontFamilyFallback: <String>['Sans Arabic']"));
      expect(source, contains("package: 'ui'"));
      expect(source, contains('height: 24 / 16'));
      expect(source, contains('fontWeight: FontWeight.w400'));
      expect(source, contains('TextStyle.lerp(a.body, b.body, t)!'));
      expect(source, contains("pick: 'selection'"));
    });

    test('is deterministic', () {
      final again = emitTokensDart(
        _fixture('pass.tokens.json'),
        options: const EmitOptions(source: 'fixture.json', fontPackage: 'ui'),
      );
      expect(again, source);
    });
  });

  test('without a font package, typography has no package argument', () {
    final source = emitTokensDart(_fixture('pass.tokens.json'));
    expect(source, isNot(contains("package: '")));
  });

  test('fontWeight tokens, escapes and reserved names', () {
    final source = emitTokensDart(
      _set({
        'font': {
          'weight': {
            'default': {r'$type': 'fontWeight', r'$value': 600},
          },
          'name': {
            'quote-mark': {r'$type': 'string', r'$value': r"it's $5"},
          },
        },
      }),
    );
    expect(source, contains('defaultValue: FontWeight.w600'));
    expect(source, contains('FontWeight.lerp(a.defaultValue'));
    expect(source, contains(r"quoteMark: 'it\'s \$5'"));
  });

  test('a typography role without an alias has no fallbacks', () {
    final source = emitTokensDart(
      _set({
        'type': {
          'body': {
            r'$type': 'typography',
            r'$value': {
              'fontFamily': 'Serif',
              'fontSize': 16,
              'fontWeight': 400,
              'lineHeight': 24,
            },
          },
        },
      }),
    );
    expect(source, isNot(contains('fontFamilyFallback')));
    expect(source, contains('letterSpacing: 0'));
  });

  final failures = <String, (Map<String, Object?>, String)>{
    'top-level token': (
      {
        'a': {r'$type': 'number', r'$value': 1},
      },
      'a: top-level tokens need a group',
    ),
    'unsupported type': (
      {
        'g': {
          'a': {r'$type': 'gradient', r'$value': 1},
        },
      },
      r'unsupported $type "gradient"',
    ),
    'bad Dart name': (
      {
        'g': {
          'a+b': {r'$type': 'number', r'$value': 1},
        },
      },
      'cannot be a Dart name',
    ),
    'string not a string': (
      {
        'g': {
          'a': {r'$type': 'string', r'$value': 1},
        },
      },
      'must be a string',
    ),
    'typography not an object': (
      {
        'g': {
          'a': {r'$type': 'typography', r'$value': 'x'},
        },
      },
      'typography must be an object',
    ),
    'typography without family': (
      {
        'g': {
          'a': {
            r'$type': 'typography',
            r'$value': {'fontSize': 1},
          },
        },
      },
      'fontFamily must be a string',
    ),
  };
  for (final MapEntry(key: name, value: (body, message)) in failures.entries) {
    test('fails: $name', () {
      expect(
        () => emitTokensDart(_set(body)),
        throwsA(
          isA<TokenException>().having(
            (e) => e.message,
            'message',
            contains(message),
          ),
        ),
      );
    });
  }

  test('the alias-cycle fixture fails to generate', () {
    expect(
      () => emitTokensDart(_fixture('fail_alias_cycle.tokens.json')),
      throwsA(isA<TokenException>()),
    );
  });
}
